[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = ["corepack enable && pnpm install || npm install"]

[phases.build]
cmds = ["pnpm run build --filter=@purple/shared && pnpm run build --filter=@purple/web || npm run build"]

[start]
cmd = "pnpm run start --filter=@purple/web || npm start"
