"""initial

Revision ID: 2edd055d8e53
Revises: 
Create Date: 2026-08-28 16:33:19.246329

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2edd055d8e53'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('global_role', sa.Enum('SUPER_ADMIN', 'ORG_ADMIN', 'ANALYST', 'VIEWER', name='userrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('organizations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('logo_url', sa.String(length=500), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'SUSPENDED', 'DELETED', name='organizationstatus'), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('settings', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organizations_slug'), 'organizations', ['slug'], unique=True)
    op.create_table('api_keys',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('key_hash', sa.String(length=255), nullable=False),
    sa.Column('key_prefix', sa.String(length=20), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'REVOKED', 'EXPIRED', name='apikeystatus'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('scopes', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_api_keys_key_hash', 'api_keys', ['key_hash'], unique=False)
    op.create_index('ix_api_keys_organization_id', 'api_keys', ['organization_id'], unique=False)
    op.create_index('ix_api_keys_user_id', 'api_keys', ['user_id'], unique=False)
    op.create_table('projects',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'ARCHIVED', 'PAUSED', name='projectstatus'), nullable=False),
    sa.Column('settings', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_projects_organization_id', 'projects', ['organization_id'], unique=False)
    op.create_index('ix_projects_owner_id', 'projects', ['owner_id'], unique=False)
    op.create_index('ix_projects_status', 'projects', ['status'], unique=False)
    op.create_table('user_organizations',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.Enum('SUPER_ADMIN', 'ORG_ADMIN', 'ANALYST', 'VIEWER', name='userrole'), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'organization_id')
    )
    op.create_table('target_apps',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.Enum('JUICE_SHOP', 'DVWA', 'CUSTOM', name='targetapptype'), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'READY', 'ERROR', 'DEPRECATED', name='targetappstatus'), nullable=False),
    sa.Column('last_validated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('validation_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_target_apps_project_id', 'target_apps', ['project_id'], unique=False)
    op.create_index('ix_target_apps_status', 'target_apps', ['status'], unique=False)
    op.create_index('ix_target_apps_type', 'target_apps', ['type'], unique=False)
    op.create_table('episodes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('target_app_id', sa.UUID(), nullable=False),
    sa.Column('scenario', sa.String(length=100), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'INITIALIZING', 'RUNNING', 'COMPLETED', 'FAILED', 'CANCELLED', name='episodestatus'), nullable=False),
    sa.Column('constraints', sa.JSON(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_app_id'], ['target_apps.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_episodes_created_at', 'episodes', ['created_at'], unique=False)
    op.create_index('ix_episodes_project_id', 'episodes', ['project_id'], unique=False)
    op.create_index('ix_episodes_scenario', 'episodes', ['scenario'], unique=False)
    op.create_index('ix_episodes_status', 'episodes', ['status'], unique=False)
    op.create_index('ix_episodes_target_app_id', 'episodes', ['target_app_id'], unique=False)
    op.create_table('attacks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('episode_id', sa.UUID(), nullable=False),
    sa.Column('technique_id', sa.String(length=50), nullable=False),
    sa.Column('owasp_category', sa.String(length=10), nullable=False),
    sa.Column('attack_type', sa.String(length=100), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('evidence', sa.JSON(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('payload', sa.Text(), nullable=True),
    sa.Column('target_endpoint', sa.String(length=500), nullable=True),
    sa.Column('http_method', sa.String(length=10), nullable=True),
    sa.Column('request_headers', sa.JSON(), nullable=True),
    sa.Column('request_body', sa.Text(), nullable=True),
    sa.Column('response_status', sa.Integer(), nullable=True),
    sa.Column('response_body', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['episode_id'], ['episodes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_attacks_episode_id', 'attacks', ['episode_id'], unique=False)
    op.create_index('ix_attacks_owasp_category', 'attacks', ['owasp_category'], unique=False)
    op.create_index('ix_attacks_success', 'attacks', ['success'], unique=False)
    op.create_index(op.f('ix_attacks_technique_id'), 'attacks', ['technique_id'], unique=False)
    op.create_index('ix_attacks_timestamp', 'attacks', ['timestamp'], unique=False)
    op.create_table('posture_scores',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('episode_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('detection_rate', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('mttr_seconds', sa.Integer(), nullable=False),
    sa.Column('coverage', sa.JSON(), nullable=False),
    sa.Column('overall_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('trend', sa.String(length=20), nullable=True),
    sa.Column('previous_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('calculated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['episode_id'], ['episodes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('episode_id')
    )
    op.create_index('ix_posture_scores_calculated_at', 'posture_scores', ['calculated_at'], unique=False)
    op.create_index('ix_posture_scores_episode_id', 'posture_scores', ['episode_id'], unique=False)
    op.create_index('ix_posture_scores_project_id', 'posture_scores', ['project_id'], unique=False)
    op.create_table('detections',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('episode_id', sa.UUID(), nullable=False),
    sa.Column('attack_id', sa.UUID(), nullable=True),
    sa.Column('detected', sa.Boolean(), nullable=False),
    sa.Column('detection_type', sa.Enum('LOG_ANALYSIS', 'REQUEST_ANALYSIS', 'PATTERN_MATCHING', 'ANOMALY_DETECTION', 'SIGNATURE_BASED', 'BEHAVIORAL_ANALYSIS', 'ML_BASED', name='detectiontype'), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.Column('matched_patterns', sa.JSON(), nullable=False),
    sa.Column('false_positive', sa.Boolean(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['attack_id'], ['attacks.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['episode_id'], ['episodes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_detections_attack_id', 'detections', ['attack_id'], unique=False)
    op.create_index('ix_detections_detected', 'detections', ['detected'], unique=False)
    op.create_index('ix_detections_detection_type', 'detections', ['detection_type'], unique=False)
    op.create_index('ix_detections_episode_id', 'detections', ['episode_id'], unique=False)
    op.create_index('ix_detections_timestamp', 'detections', ['timestamp'], unique=False)
    op.create_table('responses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('episode_id', sa.UUID(), nullable=False),
    sa.Column('detection_id', sa.UUID(), nullable=True),
    sa.Column('action_type', sa.Enum('BLOCK_IP', 'RATE_LIMIT', 'ADD_HEADER', 'MODIFY_HEADER', 'UPDATE_WAF_RULE', 'REVOKE_SESSION', 'FORCE_REAUTH', 'DISABLE_ENDPOINT', 'PATCH_VULNERABILITY', 'ADD_AUTH_CHECK', 'ENABLE_CSP', 'ENABLE_HSTS', 'CUSTOM', name='responseactiontype'), nullable=False),
    sa.Column('parameters', sa.JSON(), nullable=False),
    sa.Column('target', sa.String(length=500), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('result', sa.JSON(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('applied_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reverted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['detection_id'], ['detections.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['episode_id'], ['episodes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_responses_action_type', 'responses', ['action_type'], unique=False)
    op.create_index('ix_responses_detection_id', 'responses', ['detection_id'], unique=False)
    op.create_index('ix_responses_episode_id', 'responses', ['episode_id'], unique=False)
    op.create_index('ix_responses_success', 'responses', ['success'], unique=False)
    op.create_index('ix_responses_timestamp', 'responses', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_responses_timestamp', table_name='responses')
    op.drop_index('ix_responses_success', table_name='responses')
    op.drop_index('ix_responses_episode_id', table_name='responses')
    op.drop_index('ix_responses_detection_id', table_name='responses')
    op.drop_index('ix_responses_action_type', table_name='responses')
    op.drop_table('responses')
    op.drop_index('ix_detections_timestamp', table_name='detections')
    op.drop_index('ix_detections_episode_id', table_name='detections')
    op.drop_index('ix_detections_detection_type', table_name='detections')
    op.drop_index('ix_detections_detected', table_name='detections')
    op.drop_index('ix_detections_attack_id', table_name='detections')
    op.drop_table('detections')
    op.drop_index('ix_posture_scores_project_id', table_name='posture_scores')
    op.drop_index('ix_posture_scores_episode_id', table_name='posture_scores')
    op.drop_index('ix_posture_scores_calculated_at', table_name='posture_scores')
    op.drop_table('posture_scores')
    op.drop_index('ix_attacks_timestamp', table_name='attacks')
    op.drop_index(op.f('ix_attacks_technique_id'), table_name='attacks')
    op.drop_index('ix_attacks_success', table_name='attacks')
    op.drop_index('ix_attacks_owasp_category', table_name='attacks')
    op.drop_index('ix_attacks_episode_id', table_name='attacks')
    op.drop_table('attacks')
    op.drop_index('ix_episodes_target_app_id', table_name='episodes')
    op.drop_index('ix_episodes_status', table_name='episodes')
    op.drop_index('ix_episodes_scenario', table_name='episodes')
    op.drop_index('ix_episodes_project_id', table_name='episodes')
    op.drop_index('ix_episodes_created_at', table_name='episodes')
    op.drop_table('episodes')
    op.drop_index('ix_target_apps_type', table_name='target_apps')
    op.drop_index('ix_target_apps_status', table_name='target_apps')
    op.drop_index('ix_target_apps_project_id', table_name='target_apps')
    op.drop_table('target_apps')
    op.drop_table('user_organizations')
    op.drop_index('ix_projects_status', table_name='projects')
    op.drop_index('ix_projects_owner_id', table_name='projects')
    op.drop_index('ix_projects_organization_id', table_name='projects')
    op.drop_table('projects')
    op.drop_index('ix_api_keys_user_id', table_name='api_keys')
    op.drop_index('ix_api_keys_organization_id', table_name='api_keys')
    op.drop_index('ix_api_keys_key_hash', table_name='api_keys')
    op.drop_table('api_keys')
    op.drop_index(op.f('ix_organizations_slug'), table_name='organizations')
    op.drop_table('organizations')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###