"""make project org nullable

Revision ID: 76cb1f9a26ee
Revises: 2edd055d8e53
Create Date: 2026-08-29 00:13:28.215806

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '76cb1f9a26ee'
down_revision: Union[str, None] = '2edd055d8e53'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('projects', 'organization_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('projects', 'organization_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###